import "./globals.css";
import type { Metadata } from "next";
import { Archivo } from "next/font/google";
const inter = Archivo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-gray-100">{children}</body>
    </html>
  );
}
